### ISSUE TITLE
Bad Shipment ID for new shipments

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard-erp#12]
When a `POST api/v1/Shipments` call is made to the ERP service, the ID comes back of the form `7963ca9dda7c11392cdd51e27c6e44a4`. However, all shipments initially created are of the form `S6-331ba1af395808e6fddf3466fe218485` which can be seen by calling `GET api/v1/Shipments`. All newly created shipments should follow this format.

**Comment by jakepeyser** [comment]
fyi @l2fprod

**Comment by l2fprod** [comment]
@jakepeyser 
IDs are opaque and managed by Loopback.
Don't try to read anything out of them.
Don't show them to the end-user.

The only time where we set the ID on our own is when we seed a demo environment. In that case, the code takes the ID specified in the json file (shipment.json as example) and adds to it the demoId so that the ID is unique. This is what you see in S6-331ba1af395808e6fddf3466fe218485, S6 is the ID from shipment.json, 331ba1af395808e6fddf3466fe218485 the demoId.

When we will move to Postgres, the ID field, automatically generated by Loopback, will become a number.

**Comment by jakepeyser** [comment]
Didn't know they were managed by Loopback, but otherwise all understood. I am generally used to IDs being syntactically identical, which was why IDs of new shipments differing from initial `shipment.json` shipments sat weird with me. If we are moving to numerical IDs with Postgres, however, it seems like a moot point.
